//
// Created by gvice on 13/05/2024.
//

#ifndef WALLET_MANAGEMENT_DATACONSISTENCYEXCEPTION_H
#define WALLET_MANAGEMENT_DATACONSISTENCYEXCEPTION_H

#endif //WALLET_MANAGEMENT_DATACONSISTENCYEXCEPTION_H
